#!/bin/sh -e

for patch in *.patch; do
    patch -p1 <"$patch"
done
#sed -i 's|Liberation Mono|Monospace|g' config.def.h

# Install terminfo to right location.
export TERMINFO=$1/usr/share/terminfo
mkdir -p "$TERMINFO"

make
make PREFIX=/usr DESTDIR="$1" install
